### ISSUE TITLE
deprecated and error notations with example

### ISSUE THREAD

**Issue by jojo12** [admiralsmaster/osm_akuechler#1]
Hi, your plugin is really interesting.
In our JEM-Joomlaeventmanager we are looking for an alternative to google. (For those who don't want to be integrated in this concern.)
So I found this plugin and tried to insert your example in an article within joomla!3.8.
The map is there, looks very good! But there are some error notifications:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentOsm_akuechler has a deprecated constructor in /srv/www/vhosts/mysite.ch/httpdocs/plugins/content/Osm_akuechler/Osm_akuechler.php on line 12

Notice: Only variables should be assigned by reference in /srv/www/vhosts/my.site.ch/httpdocs/plugins/content/Osm_akuechler/Osm_akuechler.php on line 37

Notice: Only variables should be assigned by reference in /srv/www/vhosts/mysite.ch/httpdocs/plugins/content/Osm_akuechler/Osm_akuechler.php on line 91

Notice: Only variables should be assigned by reference in /srv/www/vhosts/mysite.ch/httpdocs/plugins/content/Osm_akuechler/Osm_akuechler.php on line 73

Notice: Only variables should be assigned by reference in /srv/www/vhosts/mysite.ch/httpdocs/plugins/content/Osm_akuechler/Osm_akuechler.php on line 64

Perhaps it helps you (and me) to update. Thank you a lot.

**Comment by jojo12** [comment]
For the following:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentOsm_akuechler has a deprecated constructor in /srv/www/vhosts/mysite.ch/httpdocs/plugins/content/Osm_akuechler/Osm_akuechler.php on line 12

I changed line 31
`    function __construct(&$subject, $config) {`

**Comment by jojo12** [comment]
For the following:
Notice: Only variables should be assigned by reference in....

I changed all
`& JFactory`
to
`JFactory`

**Comment by jojo12** [comment]
in addition: all http:// in the plugin should be changed to https://
if you are on http:// you then have no problems.
if you are on https:// then you get an notification of unsecure if the http:// is used!

**Comment by akuechl** [comment]
You are right. I didn't test the code for warnings. I will include the suggestions for improvement.
