### ISSUE TITLE
BUG: With Joomla! 3.9.3 the map is gone!

### ISSUE THREAD

**Issue by jojo12** [admiralsmaster/osm_akuechler#8]
Hi, with Joomla! 3.9.3 update the map is gone, even when textfilter are disabled. Your plugin is so good, but it seems Joomla! 3.9.3 is bullshit for this! Do you know a solution?

**Comment by akuechl** [comment]
The plugin version 3.9.3 works fine for me. 
See https://www.kuechler.info/osm

Did you check the log? I don't have any idea.

**Comment by jojo12** [comment]
yes, you're right. I used it together with an other plugin . And there seems to be the problem. Sorry.
[can be closed]
